### ISSUE TITLE
Implement new carousel on top of homepage

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#107]
Steve to put together technical requirements.

**Comment by kylejbertelsen** [comment]
Moved to Backlog-Improvement. Can't schedule this without any requirements.

**Comment by spaulenoff** [comment]
Related to #107

**Comment by spaulenoff** [comment]
Related to #82

**Comment by kylejbertelsen** [comment]
Missing requirements. Can't schedule.

**Comment by stevepessah** [comment]
http://www.armitageonline.co.uk/insights/how-to-create-an-image-slider-for-expression-engine

**Comment by spaulenoff** [comment]
Per Ticket #195 We need to update `<div id>` for the carousel. Outlined below:

"We'd like to implement Marketo's Real Time Personalization so we can serve personalized content to users. In order to do this, we need to update the `<div>` to be unique so Marketo knows to put X content in Y spot.

I have outlined the spots we'd like to implement this in with a proposed `<div id>`.

**NOTE: We cannot use `<div class>` to do this. It must be `<div id>`.

## In Zone Campaign

(https://docs.marketo.com/display/public/DOCS/Create+a+New+RTP+In+Zone+Campaign)

**Home page**
- Top right teal box at the top of the page <div id="top right teal">
- Bottom right box at the top of the page <div id="bottom right ad">
- We will want to put this on the slideshow also, so we need to make sure the slideshow has `<div id=homepage-slideshow>` "

**Comment by spaulenoff** [comment]
Hold off until mockup and design is added

**Comment by toshan2014** [comment]
@spaulenoff any news?

**Comment by spaulenoff** [comment]
Moved to Jira. Removed from 5/26 sprint as we are still waiting on requirements from Steve Pessah and Alla.
