### ISSUE TITLE
Mayday Article Templates: Need ablity to set global photosets, that could be added to any article

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#111]
Need ablity to set global photosets, that could be added to any article. Not just photosets on a per article basis.

Related to https://github.com/akcdotorg/akc.org/issues/81

**Comment by kylejbertelsen** [comment]
Questions that need to be answered before adding to a sprint:
-- These photogalleries are of the currently-existing photo gallery type, yes?
-- They should be selected on (a) an article-by-article basis, or (b) by Content Pages category?
-- Embedded gallery chosen by this field is ignored when the photo gallery grid fields in the article are populated, yes?

Can be done as follows:
-- create a Relationship field in Articles, which limits the dropdown to type media, category photogallery, sort date descending (so the newest ones are on top)
-- in template, if the photo gallery grid fields are populated, ignore this field. Otherwise, display this embedded gallery as you would as though it was entered in this Article's grid fields.

**Comment by spaulenoff** [comment]
My answers and notes below in bold. @elieo please advise as well
-- These photogalleries are of the currently-existing photo gallery type, yes? **Yes**
-- They should be selected on (a) an article-by-article basis, or (b) by Content Pages category? **@elieo please confirm**
-- Embedded gallery chosen by this field is ignored when the photo gallery grid fields in the article are populated, yes? **@elieo Please confirm**

Can be done as follows:
-- create a Relationship field in Articles, which limits the dropdown to type media, category photogallery, sort date descending (so the newest ones are on top)
-- in template, if the photo gallery grid fields are populated, ignore this field. Otherwise, display this embedded gallery as you would as though it was entered in this Article's grid fields.

**Comment by elieo** [comment]
@spaulenoff @kylejbertelsen   I don't fully understand all your questions. can we please set up a time to review this in person.

**Comment by spaulenoff** [comment]
Moved to Jira
