### ISSUE TITLE
Add external link functionality to breed standard on FSS breed pages

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#15]
https://akcorg.atlassian.net/browse/AKC2-129

**Comment by spaulenoff** [comment]
Right now the only way to add a "breed standard" on the breed pages is to upload a PDF in the backend. We need to create the functionality to allow us to externally link to other websites, instead of only being able to upload our own PDFs.
This is important because the FSS breeds have a breed standard that is hosted on another website, which we do not control.
![image](https://cloud.githubusercontent.com/assets/13648969/13398988/fb299236-dece-11e5-9171-f6a8d150184e.png)

For example, on this page: http://www.akc.org/dog-breeds/appenzeller-sennenhunde/ when a user rolls over the "breed standard section" (not there currently because nothing is uploaded) they should get directed to: http://www.fci.be/Nomenclature/Standards/046g02-en.pdf in a new tab.
![image](https://cloud.githubusercontent.com/assets/13648969/13398998/06981cbe-decf-11e5-8178-578f307e41bc.png)

**Comment by stevepessah** [comment]
Moved to JIRA
