### ISSUE TITLE
Content Hubs: Remove Old Content Hub URL structures

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#157]
Need to remove old content url structures:
http://www.akc.org/media/
http://www.akc.org/article/
http://www.akc.org/media/article/{content title} - example: http://www.akc.org/media/article/ovulation-in-the-bitch
http://www.akc.org/media/view/{content title} - Example: http://www.akc.org/media/view/common-dangerous-foods-for-your-dog

**Comment by spaulenoff** [comment]
Also need to close the following URLs https://www.google.com/search?q=site%3Bhttp%3A%2F%2Fwww.akc.org%2Fmedia%2Farticle%2Fwait-until-you-hear-how-this-lab-snores%2F&oq=site%3Bhttp%3A%2F%2Fwww.akc.org%2Fmedia%2Farticle%2Fwait-until-you-hear-how-this-lab-snores%2F&aqs=chrome..69i57j69i58.1823j0j1&sourceid=chrome&ie=UTF-8#q=site:http://www.akc.org/media/&start=0

**Comment by spaulenoff** [comment]
related to #7

**Comment by kylejbertelsen** [comment]
404 'em

**Comment by toshan2014** [comment]
Instead of creating redirections, I've removed the template groups "media" and "article". This ensures that's there no redundant templates. I've discussed this approach with Kyle and he's OK with it.

Although this should not affect any Mayday content on "/content", please double check at least an article, photo-gallery and video page are displaying within "/content".

please QA
http://develop2.akc.org/media/
http://develop2.akc.org/article/
http://develop2.akc.org/article/akc-training/
http://develop2.akc.org/media/view/test-photo-gallery

As mentioned above please verify that photo gallery, video and article are working under "/content". Ex:
http://develop2.akc.org/content/westminster-dog-show/articles/masters-agility-and-obedience-results/

**Comment by toshan2014** [comment]
Time : 3h

**Comment by spaulenoff** [comment]
Verified on Dev2

**Comment by toshan2014** [comment]
stg:
http://stage-ng.akc.org/media/
http://stage-ng.akc.org/article/
http://stage-ng.akc.org/article/akc-training/
http://stage-ng.akc.org/media/view/test-photo-gallery/

**Comment by toshan2014** [comment]
pf please QA
http://develop2.akc.org/media/
http://develop2.akc.org/article/
http://develop2.akc.org/article/akc-training/
http://develop2.akc.org/media/view/test-photo-gallery

**Comment by spaulenoff** [comment]
Verified on Prod
