### ISSUE TITLE
Mobile Video Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#183]
Subticket of #173

http://www.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/

Change:
Ad 320x50 (x10) between title and video

**Ads on page after change**: x10

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/new_video_page__mobile_ads_720.png

**Comment by toshan2014** [comment]
Please QA: http://develop2.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/

Time : 1h

**Comment by toshan2014** [comment]
stg: http://stage-ng.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/

**Comment by aalattili** [comment]
@spaulenoff 
Ad displays without borders ,moreover, there is no breathing area between videos and descriptive text. (content_videos.jpg)
![content_videos](https://cloud.githubusercontent.com/assets/12289479/14853475/513edd1e-0c94-11e6-8f6c-2d3d7c6ca314.jpg)

**Comment by spaulenoff** [comment]
@toshan2014 Can you update per Alaa's comment?

**Comment by toshan2014** [comment]
@spaulenoff 
I've left out the borders on purpose as in this case the ad blends better without them. Otherwise it creates sort of a separation between the title and the video.
For the spacing issue, I've added some space between the video and text.

pf: http://stage-ng.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/

**Comment by toshan2014** [comment]
Time spent: 1.5h

**Comment by toshan2014** [comment]
prod : http://www.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/

**Comment by spaulenoff** [comment]
Verified on Prod
