### ISSUE TITLE
Add Teads In-Content Video code to Browse all breeds page

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#206]
Related to #164 

We want to add the teads code with an ability to turn on and off to the browse all breeds page:
http://www.akc.org/dog-breeds/
http://www.akc.org/dog-breeds/?letter=B
http://www.akc.org/dog-breeds/?letter=L
ETC...

**Comment by skt2** [comment]
Getting error for teads, I will follow up with support about this:
Resource interpreted as Document but transferred with MIME type image/gif: "http://ums.adtechjp.com/mapuser?providerid=1053;userid=nWrfmZ4_18uFb4yczD7Dzs1p3M6FZdnIm2U8QUjw&cfp".

Font from origin 'http://cdn.teads.tv' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://local.akc.org' is therefore not allowed access.

**Comment by skt2** [comment]
Reply from Teads Support: @elieo @stevepessah @spaulenoff 
I'll have an updated tag for you soon that will be able to serve to that page.
Our tag looks for slots within a page as a location to deliver to. If there is a page that has a different layout than the pages that the tag has been created for, it will likely not deliver because there is no location for the ad to display. That is the case with the dog breads page, so we'll get it updated so you can serve there.

**Comment by skt2** [comment]
Time Spent: 3h

Tested Here: http://develop2.akc.org/dog-breeds/

**Comment by AKCOsama** [comment]
@spaulenoff I cannot understand what teads code should be added and how to test?

**Comment by spaulenoff** [comment]
That is fine @AKCOsama I have already verified this ticket

**Comment by spaulenoff** [comment]
Verified on Prod
