### ISSUE TITLE
Desktop Homepage Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#212]
Subticket of #211

http://elieorgel.com/wp-content/uploads/2016/04/Homepage.png

Changes:
Add 728x90 (x03) inbetween Featured Breeds and featured stories section
Remove 728x90 (x03) from bottom of the page

Adds on page after changes x01 (300x250), x11 (300x250), x03 (728x90)

**Comment by toshan2014** [comment]
dev2: http://develop2.akc.org/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/

**Comment by aalattili** [comment]
@spaulenoff 
Develop2: Ads (x01 , x11 , x03) are verified 
![develop2-home page ads](https://cloud.githubusercontent.com/assets/12289479/14983445/2480bee4-1146-11e6-9b67-2a290b5d732b.jpg)

Stage: 
- Ads (x01 , x11) are verified
- Ad (x03) not verified: 
  1. Displays as (728x91) instead of (728x90)
  2. Doesn't have an iframe id ("oas_frame_x03")
     ![stage-home page ads](https://cloud.githubusercontent.com/assets/12289479/14983605/0453f5cc-1147-11e6-93f6-d688615038e3.jpg)

**Comment by spaulenoff** [comment]
@toshan2014 Please update per Alaa's comments above

**Comment by toshan2014** [comment]
@spaulenoff 
This is due to some images supplied by the ad server having inconsistencies in size. Some are perfectly cut 728x90, others are not. See attached screenshot. Best to keep this this way rather than resize on our end.

<img width="960" alt="ad-size" src="https://cloud.githubusercontent.com/assets/6847220/14988836/77a92f20-110a-11e6-86a8-82c0f9fa15b7.png">

**Comment by spaulenoff** [comment]
Ok Verified on Stage

**Comment by aalattili** [comment]
Verified on preflight

**Comment by toshan2014** [comment]
pf: http://stage-ng.akc.org/

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by toshan2014** [comment]
prod http://www.akc.org/

**Comment by spaulenoff** [comment]
Verified on Prod

**Comment by toshan2014** [comment]
Time spent : 40min
