### ISSUE TITLE
Desktop Breed Detail Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#214]
Subticket of #211

http://www.akc.org/dog-breeds/pug/detail/

Changes:
Add 728x90 (x13) at the top of the page

http://elieorgel.com/wp-content/uploads/2016/04/breed-detail-page.png

Ads on Page after Update -  x03 and x13

**Comment by toshan2014** [comment]
dev 2 http://develop2.akc.org/dog-breeds/pug/detail/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/dog-breeds/pug/detail/

**Comment by aalattili** [comment]
@spaulenoff 
Develop2: 
- Ad (x03 ) is verified
- Ad (x13) isn't verified. Ad displays as (729x90) instead of (728x90)
  ![develop2-breed details page ads](https://cloud.githubusercontent.com/assets/12289479/14984075/956975e4-1149-11e6-9fd4-373a1a839944.jpg)

Stage: Ads (x03 and x13) are verified
![stage-breed details page ads](https://cloud.githubusercontent.com/assets/12289479/14984091/a8ec8f48-1149-11e6-84bd-19c67cf604ae.jpg)

**Comment by toshan2014** [comment]
Time spent: 45min

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf: http://stage-ng.akc.org/dog-breeds/pug/detail/

**Comment by toshan2014** [comment]
prod: 
http://www.akc.org/dog-breeds/pug/detail/

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by spaulenoff** [comment]
Verified on Prod
