### ISSUE TITLE
Desktop Events Category Overview Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#219]
Subticket of #211

http://www.akc.org/events/

Changes:
Add 728x90 (x03) between hero/unhero and breadcrumb

http://elieorgel.com/wp-content/uploads/2016/04/Events-Category-Overview.png

Ads on Page after Update - x01, x03 and x05

**Comment by toshan2014** [comment]
dev2 http://develop2.akc.org/events/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/events/

**Comment by aalattili** [comment]
@spaulenoff 
General issues: 
- No proper breathing area between x01 & 05 Ads
- Ad x03 doesn't have an ifram id ("oas_frame_x03")

Develop2: 
- Ads x01 and x03 are verified 
- Ad x05 isn't verified:
  1. Ad box size is verified
  2. Ad image size isn't verified, since it doesn't proper fit in Ad box.
     ![develop2-event page ads](https://cloud.githubusercontent.com/assets/12289479/14984501/b9188f82-114b-11e6-8d35-8eb38c504377.jpg)

Stage: Ads (x01, x03 and x05) are verified
![stage-event page ads](https://cloud.githubusercontent.com/assets/12289479/14984527/d57ac834-114b-11e6-9e28-62598fafc1d7.jpg)

**Comment by toshan2014** [comment]
Time spent: 40min

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf : 
http://stage-ng.akc.org/events/

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by toshan2014** [comment]
prod http://www.akc.org/events/

**Comment by spaulenoff** [comment]
Verified on Prod
