### ISSUE TITLE
Ads Reloading on certain pages

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#244]
We see ads reloading on several pages after a few second and we need to figure out why this is occurring and resolve this issue:

Examples:
http://www.akc.org/learn/dog-health/cephalexin-for-dogs/
http://www.akc.org/content/health/
http://www.akc.org/content/dog-breeding/articles/ovulation-in-the-bitch/
http://www.akc.org/content/health/videos/yogurt-popsicles-treats-for-dogs/

**Comment by toshan2014** [comment]
It seems that this was due to the naming convention used for some ads in certain pages were conflicting and they were being loaded. Should be fixed now. Please QA:

http://develop2.akc.org/learn/akc-gazette/the-akc-gazette-celebrating-the-sport-of-dogs/
http://develop2.akc.org/content/dog-breeding/
http://develop2.akc.org/content/dog-breeding/tips-from-experts/
http://develop2.akc.org/content/dog-breeding/articles/matching-puppies-with-the-right-homes/
http://develop2.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/

**Comment by spaulenoff** [comment]
Sent to Yourbow to check over

**Comment by spaulenoff** [comment]
Verified per Yourbow's Email

**Comment by toshan2014** [comment]
Stage:
http://stage-ng.akc.org/content/dog-breeding/articles/ovulation-in-the-bitch/
http://stage-ng.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/
http://stage-ng.akc.org/content/dog-care/photo-galleries/common-dangerous-foods-for-your-dog/
http://stage-ng.akc.org/content/dog-breeding/tips-from-experts/
http://stage-ng.akc.org/content/dog-breeding/

http://stage-ng.akc.org/learn/
http://stage-ng.akc.org/learn/akc-gazette/the-akc-gazette-celebrating-the-sport-of-dogs/

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on dev2 & stage

**Comment by toshan2014** [comment]
Found out that this issue was due to ids such as `<span id="oas_x10">` were making two calls. It's likely that this naming format is being used for other purposes internally. Changing the format to `<span id="ad-oas-x10">` resolved the problem.

Time spent: 2.5h

**Comment by spaulenoff** [comment]
Verified on Prod per Yourbow
