### ISSUE TITLE
Unformatted chars 

### ISSUE THREAD

**Issue by toshan2014** [akcdotorg/akc.org#250]
http://stage-ng.akc.org/dog-breeds/?letter=B

See attachment: 
<img width="862" alt="unformatted_chars" src="https://cloud.githubusercontent.com/assets/6847220/15190332/35e68762-1764-11e6-9774-ca53fbaab366.PNG">

**Comment by stevepessah** [comment]
We had resolved this issue before and it's back again, FYI.

**Comment by stevepessah** [comment]
Another example can be found here - https://github.com/akcdotorg/akc.org/issues/97

Needs to be updated throughout site.

**Comment by skt2** [comment]
In first example, it seems title is copied from somewhere so the dash(-) is some different character. when I changed  – to dash( - ) in my local CMS, it solved the problem.
National Purebred Dog Day is May 1 – Show your Support 
National Purebred Dog Day is May 1 - Show your Support
If this is the case then we might need to be careful while adding content though I'll keep looking into this but just to make sure that this is not happening due to copy & paste content from somewhere.

![screen shot 2016-05-12 at 4 47 44 pm](https://cloud.githubusercontent.com/assets/16002526/15229948/54443742-1861-11e6-9e9e-2b1f7cb21cc2.png)

**Comment by skt2** [comment]
Tested Here: http://develop2.akc.org/dog-breeds/
![unformatted_chars](https://cloud.githubusercontent.com/assets/16002526/15372515/c5bff56c-1d0e-11e6-88e3-04241e469b87.png)

**Comment by skt2** [comment]
For this to work, I have removed, `{exp:akc_apps_path_env:outputCorrectDomainBasedOnEnv}`
the markup was wrapped inside this and that was causing the issue, I don't see any issue by removing this but @spaulenoff please ask Aspire to QA is throughly if they can find any issue.

**Comment by skt2** [comment]
Tested here: http://stage-ng.akc.org/dog-breeds/

**Comment by aalattili** [comment]
@spaulenoff & @skt2 
QA retesting passed on dev2 & stage across browsers (GC 50, FF 45 & IE 11).

**Comment by skt2** [comment]
Time Spent: 3h

**Comment by aalattili** [comment]
@spaulenoff 
Verified on prod, no article was found with same issue but couldn't find the article used to have it

**Comment by spaulenoff** [comment]
Verifiedo n Prod
