### ISSUE TITLE
PROJECT: Security issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#26]
https://akcorg.atlassian.net/browse/AKC2-128

**Comment by spaulenoff** [comment]
1- Cross-site scripting:
XSS (Cross-site Scripting) allows an attacker to execute a dynamic script (Javascript, VbScript) in the context of the application. This allows several different attack opportunities, mostly hijacking the current session of the user or changing the look of the page by changing the HTML on the fly to steal the user's credentials. This happens because the input entered by a user has been interprete as HTML/Javascript/VbScript by the browser. 
XSS targets the users of the application instead of the server. Although this is a limitation, since it allows attackers to hijack other users' session, an attacker might attack an administrator to gain full control over the application.
2- Permanent cross-site scripting:
Permanent means that the attack will be stored in the back end system. In normal XSS attacks an attack needs to e-mail the victim but in a permanent XSS an attacker can just execute the attack and wait for users to see the affected page. As soon as someone visits the page, the attacker's stored payload will get executed.
3- Basic authentication over clear text:
The application is using Basic Authentication over HTTP, which sends username and password in plain text.
4- Possible permanent cross site scripting
Note:
Please refer to attached pdf for full security scan report
[www.akc.org_28thAug.pdf](https://github.com/akcdotorg/akc.org/files/151204/www.akc.org_28thAug.pdf)

**Comment by stevepessah** [comment]
@kylejbertelsen is this still open?
