### ISSUE TITLE
Reset Password emails not received by end user

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#31]
Gigya's reset password email does not get sent out to an unverified email address. To overcome this issue we can implement this solution suggested by Gigya support.

B. Using RaaS markup extensions, make the following changes to the markup of your forgot password screen: 

1) Add this javascript function to the page: 

function sendemail(val) { 
document.getElementById('emailID').value = val; 
} 

2) Add to the input field named loginID the onchange event in the gigya-forgot-password-screen: 

<input type="text" name="loginID" class="gigya-input-text" tabindex="0" onchange="sendemail(this.value);"> 

3) Add this hidden input field to the gigya-forgot-password-screen.

<input id="emailID" type="hidden" name="email" class="gigya-input-text" tabindex="0">

This will cause the forgot password screen to send an additional parameter "email" to the internal accounts.resetPassword request that it is making, and this will send out the password reset email regardless of whether the user has verified their email address.

**Comment by toshan2014** [comment]
To test the issue: 
- I created a new screen set **Login-web-2** in the GigyaConsole
- Set "public_html/src/js/lib/gigya/LoginIntegration.js" to point to **Login-web-2** instead of **Login-web**
- Then I created a new account using the Sign-Up and while the email address used was "unverified" (meaning I did not click on a link to confirm the email from my inbox), I tried the Forgot Password feature and it worked fine. I got an reset password link for the email I had provided. 

Spoke to Purvi about it and apparently it could be an intermittent issue. It works fine for some emails while it does not for others.

Applying the suggested solution is coming up with the following JS error:

<img width="513" alt="31-js-error" src="https://cloud.githubusercontent.com/assets/6847220/14002705/ddd1b5f8-f10a-11e5-89ad-9342ea29272a.PNG">

The issue is that the JS function highlighted is not being executed in the Raas Markup extension:
- Gigyal Console > Registration-as-a-Service > Screen-sets > Login-web-2 

<img width="561" alt="31-js-function" src="https://cloud.githubusercontent.com/assets/6847220/14002723/f9b719a2-f10a-11e5-8736-41bb7b426e49.PNG">

I've also tried putting the  JS function in "public_html/src/js/lib/gigya/LoginIntegration.js" and it still does not execute.

I've reverted back to Login-web for now.

Will need speak to Purvi/Kyle tomorrow.

**Comment by kylejbertelsen** [comment]
Where is the 'missing' function called from? You might have some luck from recajiggering the load-order of the JavaScripts.

**Comment by toshan2014** [comment]
@kylejbertelsen From the Raas Markup ( which is on the gigya console ) as suggested by the solution. I'll try loading that JS after everything else.

**Comment by toshan2014** [comment]
Tried adding the 'sendemail' function in public_html/src/js/lib/gigya/LoginIntegration.js using 'load' event. But that did not work either. I'll need some help with this.

**Comment by pps2010** [comment]
sendemail function has to be added in ....

1) Add this javascript function to the page:
function sendemail(val) { 
document.getElementById('emailID').value = val; 
}

Was this done?

**Comment by toshan2014** [comment]
@pps2010 Yes I tried to add it in the Gigya Raas Markup and in LoginIntegration.js - neither worked.

**Comment by toshan2014** [comment]
Email sent to Gigya support (3/28/2016):

Hi Joshua

We've tried to implement the suggested solution but it seems that the JS function is undetected in the Raas Markup. Please see the attached screenshots and let me know if we're going wrong somewhere.

FYI. The 'sendemail' function is in screen set Login-web-2 in the GigyaConsole. You can test this out on http://develop2.akc.org/ > Sign In > Forgot Password > Enter an email address > Submit. I've also tried adding it to an external JS file with the same result.

Thanks
Toshan

**Comment by toshan2014** [comment]
@spaulenoff Time spent so far: 3h

**Comment by toshan2014** [comment]
Reply from Gigya (03/29/2016):

Hi Toshan,

This is Joshua from Gigya following up with you on this matter. My apologies if I was unclear earlier, please include the sendemail function on the page and not in the markup of the screen-sets.

I've done a demonstration page for you that can be used as a reference: https://joshua.gigya-cs.com/Demos/raas/passwordResetSendEmail/
1. Click "Register" and complete the registration process until you are sucessfully logged-in.
2. Click "Logout"
3. Click "Login" => "Forgot Password"
4. Enter your email address and click "Submit".

I used the onBeforeSubmit event to add in an 'alert' that triggers whenever you submit the forgot password screen to show the parameters that are being passed. You should be able to see that both "loginID" and "email" are being passed as parameters.

Thank you for your kind attention to this matter. I hope this helps!

Warmest Regards,
Joshua Tan

**Comment by toshan2014** [comment]
Attempting solution now... I'll update soon

**Comment by toshan2014** [comment]
The above solution provided seems to work, meaning there's no JS errors anymore.

However to actually test out if the solution as a whole fixes the 'Reset Password' issue, we'll need to check with users who have been experiencing the problem. 

@pps2010 Any idea if that's something we can do?

**Comment by toshan2014** [comment]
Time spent : 4.5h

**Comment by toshan2014** [comment]
looks to  be working stg

**Comment by toshan2014** [comment]
verified on pf: develop2.akc.org/

**Comment by toshan2014** [comment]
Verified that the forgot password functionality is working and that the solution provided by Gigya is present on Production. 
Remains to be seen if the actual issue is resolved - 
@pps2010 @spaulenoff

**Comment by stevepessah** [comment]
@spaulenoff @pps2010 any update on this?

**Comment by toshan2014** [comment]
Had a discussion with Purvi as to why this is not working for Marketplace. Turns out that Marketplace is still using the original screen in the Gigya Console. I'll make the change on the original screen ( Login-Web ) so that both AKC.org and Marketplace use the same screen.
I'll update this ticket once done.

**Comment by toshan2014** [comment]
@pps2010 the following function needs to be added to Marketplace otherwise Login-Web will come up with a JS error. Please refer to view-source in akc.org line 2860 for example:

`<script type='text/javascript'>
    // Gigya's fix for reset password email does not get sent out to an unverified email address
    function sendemail(val) {
        document.getElementById('emailID').value = val;
    }
</script>`

**Comment by toshan2014** [comment]
Quick update - 
Keeping "Login-web-2" for AKC.org
Gabriel from the marketplace team will do the changes on their side. No more changes required for AKC.org for this ticket.
