### ISSUE TITLE
PROJECT - Sitespeed Issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#61]
https://akcorg.atlassian.net/browse/AKC2-403

**Comment by spaulenoff** [comment]
IMPORTANT NOTE ON THIS PROJECT, and on each of the subtickets in this project:

_Each ticket must be in its own unique branch._ The reason for this is: We'd like to be able to see how much impact each of these improvements makes in the bottom-line of performance. In order to gauge that, what we'll do:
1. checkout master on a server
2. run our performance test on that server
3. save the reports generated in 2
4. checkout your branch on that server
5. run our performance test on that server
6. save the reports generated in 5
7. add both those reports to the ticket, so we can compare them

Goal - To lower Page load time

Milestones:
- First Release in February - 15 Second Page Load Time
- Overall Goal for end of Quarter - 10-11 Second Page Load Time

AKC Homepage - 18.09 Seconds
http://www.webpagetest.org/result/151218_C9_YW0/ 

_Similar sites in terms of page weight:_

Buzzfeed - 14.38 Seconds
http://www.webpagetest.org/result/151218_VD_ZNW/

Bleacher Report - 12.01 Seconds
http://www.webpagetest.org/result/151218_HJ_ZP4/

Huff Post - 9.95 Seconds
http://www.webpagetest.org/result/151218_E6_ZPD/

_Direct competitors:_

The Dodo - 1.3 Seconds 
http://www.webpagetest.org/result/151220_0R_2XF/

Pet MD - 22.12 Seconds
http://www.webpagetest.org/result/160105_SK_W7X/

Dog Time - 9.46 Seconds
http://www.webpagetest.org/result/160105_MW_WBG/

Pet 360 - 7.89 Seconds
http://www.webpagetest.org/result/160105_Q5_WD6/

Barkpost - 10.09 Seconds
http://www.webpagetest.org/result/160105_DC_WFD/

**Comment by spaulenoff** [comment]
Broken into sub Tickets As seen below:
https://github.com/akcdotorg/akc.org/issues/69 (Site-speed - Image file size issues)
https://github.com/akcdotorg/akc.org/issues/70 (Sitespeed - Compress, combine and minify CSS files across akc.org)
https://github.com/akcdotorg/akc.org/issues/71 (Sitespeed - Figure out how we want to load ad networks on the site)
https://github.com/akcdotorg/akc.org/issues/72 (Sitespeed - Remove Remnant Ads on Homepage)
https://github.com/akcdotorg/akc.org/issues/73 (Sitespeed - Combine JS files and Minify them across AKC.org)
https://github.com/akcdotorg/akc.org/issues/74 (Sitespeed - Make it so there is only one Global fav icon for the site )
https://github.com/akcdotorg/akc.org/issues/75 (Sitespeed - Remove google maps calls from the site)
https://github.com/akcdotorg/akc.org/issues/76 (Sitespeed: Implement AMP on mobile pages)
#136 (Sitespeed: Research and Evaluate AMP Project)

**Comment by spaulenoff** [comment]
Sitespeed before pushes on Dev2:
![image](https://cloud.githubusercontent.com/assets/13648969/13401233/51fd0de0-ded9-11e5-8d9c-49f65a7ad5c2.png)
