### ISSUE TITLE
PROJECT - Westmemester - Figure out database issue so we can push this without the site slowing/crashing

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#68]
https://akcorg.atlassian.net/browse/AKC2-110

**Comment by spaulenoff** [comment]
All the work was done correctly for this but when we tried pushing it to prod twice, it caused the site to slow due to a database issue. Purvi had looked into it but we never came up with a solution. This was one of the original apps that we paid for in the original akc.org build.
https://github.com/itsMakeable/akc.org/issues/75
Note: to ensure we don't lose the information on the makeable github, that page is archived in the attached zip file.

**Comment by spaulenoff** [comment]
[akc2-110.zip](https://github.com/akcdotorg/akc.org/files/151322/akc2-110.zip)

**Comment by spaulenoff** [comment]
Added to Jira
