### ISSUE TITLE
Sitespeed - Combine JS files and Minify them across AKC.org

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#73]
See #161

**Comment by kylejbertelsen** [comment]
We want to have a process that minifies JS outside of gulp, since we want to get rid of gulp.

**Comment by skt2** [comment]
Time Spent: 6h

How to QA: @spaulenoff 
1. Make sure top menu is working fine.
2. Footer is working fine.
3. Gigya login is working fine
4. Ads are working fine across the site
5. Pages with use of JS is working fine. (/find-a-match)
6. View source: you only see one JS file instead of list of files. (/cache/...)
7. Check and see if you find difference on site speed test. (May be this won't have perfect results on dev2 or stage but please do this for production before and after deployment)

**Comment by spaulenoff** [comment]
Looks good to me. I am going to have Aspire look over the site this weekend to confirm though.

**Comment by spaulenoff** [comment]
Header and footer seem to be working for me

**Comment by spaulenoff** [comment]
Caused issues when pushed to production. Need to revisit to see if there is a better way to handle this ticket

**Comment by skt2** [comment]
Preliminary investigation: Minimee is not compatible with Varnish cache.

**Comment by skt2** [comment]
Issue related links:
https://devot-ee.com/add-ons/support/minimee/viewthread/2379
https://devot-ee.com/add-ons/support/minimee/viewthread/4914

**Comment by skt2** [comment]
https://devot-ee.com/add-ons/support/minimee/viewthread/15703 -- Please see the reply.

**Comment by kylejbertelsen** [comment]
Time-tracking, Kyle: 2016-04-06  -- 1 hour

**Comment by spaulenoff** [comment]
@aalattili @AKCOsama Please check over stage-ng to ensure site is stable

**Comment by aalattili** [comment]
@spaulenoff ,Stage-ng site seems stable and working fine

**Comment by kylejbertelsen** [comment]
Closing this ticket, in favor of the more-recent #161. Testing should occur within that ticket.
